### ISSUE TITLE
`Gurl, the DSL you gave me is so wrong. This is a Camel Route not a null` in output log of Kaoto backend for almost all routes

### ISSUE THREAD

**Issue by apupier** [KaotoIO/vscode-kaoto#129]
for instance, with:

```
- from:
    uri: timer:demo
    steps:
    - to:
        uri: twitter-directmessage:example
```
