### ISSUE TITLE
Integration name is always set back to `integration` when opening the file

### ISSUE THREAD

**Issue by apupier** [KaotoIO/vscode-kaoto#45]
- create file name;kaoto.yaml with content:
  ```yaml
  apiVersion: camel.apache.org/v1alpha1
  kind: KameletBinding
  metadata:
    name: myName
  spec: {}
  ```
- Open it with Kaoto Editor
- The name is set back to default which is `integration`

![nameSetBackToIntegration](https://user-images.githubusercontent.com/1105127/196145051-34641101-88e3-4760-9ff3-3f83ee92d0db.gif)
